### ISSUE TITLE
As a backend developer, I want to create a dog parks API endpoint so that I can use the data on the front end UI

### ISSUE THREAD

**Issue by darrendaz** [darrendaz/dog-park-locator#5]
API endpoint should repond with JSON

**Comment by BMWeygant** [comment]
Believe this has been resolved with the updates to Backend Development branch. Please merge with master when you're ready to proceed.

**Comment by darrendaz** [comment]
@

**Comment by darrendaz** [comment]
@BMWeygant what are the urls for the endpoints?
